version: "3.9"

services:

  #################################################
  # API Gateway
  #################################################

  apigateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - product.api
      - order.api
      - notification.api
      - keycloak
    networks:
      - microservice-network

  #################################################
  # Product Service
  #################################################

  product.api:
    container_name: product.api
    build:
      context: .
      dockerfile: Product/Dockerfile
    ports:
      - "7001:8080"
    networks:
      - microservice-network
    depends_on:
       - rabbitmq
  #################################################
  # Order Service
  #################################################

  order.api:
    container_name: order.api
    build:
      context: .
      dockerfile: Order/Dockerfile
    ports:
      - "7002:8080"
    networks:
      - microservice-network
    depends_on:
       - rabbitmq
  #################################################
  # Notification Service
  #################################################

  notification.api:
    container_name: notification.api
    build:
      context: .
      dockerfile: Notification/Dockerfile
    ports:
      - "7003:8080"
    networks:
      - microservice-network
    depends_on:
       - rabbitmq
  #################################################
  # Rabbitmq 
  #################################################
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    networks:
      - microservice-network
  #################################################
  # PostgreSQL (Keycloak)
  #################################################

  keycloak-db:
    image: postgres:17
    container_name: keycloak-db
    restart: always

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

    networks:
      - microservice-network

  #################################################
  # Keycloak
  #################################################

  keycloak:
    image: keycloak/keycloak:26.6.4
    container_name: keycloak

    command: start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

    depends_on:
      - keycloak-db

    ports:
      - "7004:8080"

    networks:
      - microservice-network

#################################################
# Network
#################################################

networks:
  microservice-network:
    driver: bridge

#################################################
# Volumes
#################################################

volumes:
  keycloak-db-data: